version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
    - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped


  gestion_des_fichiers:
    restart: always
    container_name: gestion_des_fichiers
    build:
      context: ./backend/gestion_des_fichiers
      dockerfile: Dockerfile
    expose:
      - "8090"
    depends_on:
      - db
    networks:
      - app-network


  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    links:
           - "gestion_des_fichiers"
    depends_on:
           - "gestion_des_fichiers"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge